<?php
    /** @var \Magento\Checkout\Block\Checkout\Layout\Processor $block */
    $customerSession = $block->getCustomerSession();
    $email           = '';
    if ($customerSession->isLoggedIn()) {
        $email = $customerSession->getCustomer()->getEmail();
    }
?>
<div class="field">
    <label for="email" class="label"><span><?php echo __('Email Address')?></span></label>
    <div class="control">
        <input type="email" name="email" id="email" value="<?php echo $email?>" class="input-text" />
    </div>
</div>
