<?php

/** @var $block Magento\Framework\View\Element\Template */
/**
 * @var  $shippingConfigViewModel Nishant\FreeShippingPromo\ViewModel\ShippingConfig
 */
$shippingConfigViewModel = $block->getData('shipping_config_view_model');
$jsLayout = json_decode($block->getJsLayout(), true);
$jsLayout['components']['free-shipping-banner']['config']['freeShippingThreshold'] = $shippingConfigViewModel->getFreeShippingThreshold();
?>
<div id="free-shipping" data-bind="scope: 'free-shipping'">
     <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "#free-shipping": {
            "Magento_Ui/js/core/app": <?=json_encode($jsLayout)?>
        }
    }
</script>
